[package]
name = "oak_stage0"
version = "0.1.0"
authors = ["Andri Saar <andrisaar@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
bitflags = "*"
elf = { version = "*", default-features = false }
log = "*"
<<<<<<< HEAD
coset = {version = "0.3.4", default-features = false}
=======
linked_list_allocator = "*"
>>>>>>> 8fb273ea5232aa1e6080696aa320073fe6d47adf
oak_core = { path = "../oak_core", default-features = false }
oak_linux_boot_params = { path = "../linux_boot_params" }
oak_sev_guest = { path = "../oak_sev_guest", default-features = false }
sev_serial = { path = "../sev_serial" }
sha2 = { version = "*", default-features = false, features = ["force-soft"] }
spinning_top = "*"
static_assertions = "*"
strum = { version = "*", default-features = false, features = ["derive"] }
x86_64 = "*"
zerocopy = "*"
p384 = { version = "0.13.0", default-features = false, features = ["ecdsa"]}
hkdf = {version = "0.12.3", default-features = false}
sha2 = {version = "0.10.7", default-features = false}
rand_core = {version = "0.6.4", default-features = false, features = ["getrandom"]}
hex = { version = "0.4", default-features = false, features = ["alloc"] }